#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path
from typing import Dict, List


DEFAULT_FIELDS: List[str] = ["system_prompt", "prompt", "response"]


def clean_text(text: str) -> str:
    """
    Conservative cleanup:
    - normalize newlines
    - remove common mojibake sequences (e.g., �~F~R)
    - fix a few known broken tokens
    - collapse excessive blank lines
    """
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Remove common mojibake sequences like �~F~R, �~I�, �~H~^ etc.
    text = re.sub(r"�~[^\s]{1,20}", "", text)

    # Fix duplicated punctuation
    text = text.replace("::\n:\n", ":\n")
    text = text.replace("::", ":")

    # Fix ENUU / ENU U
    text = re.sub(r"\bENUU+\b", "ENU", text)
    text = re.sub(r"\bENU\s*U\b", "ENU", text)

    # Fix broken tokens (best-effort)
    text = re.sub(r"E\s*X+\s*X*\s*E\s*C\s*T\s*E\s*D", "EXPECTED", text, flags=re.IGNORECASE)
    text = re.sub(r"SUPPLEMENT\s*T+\s*ARY", "SUPPLEMENTARY", text, flags=re.IGNORECASE)

    # Small typos
    text = re.sub(r"\bfeaturee\b", "feature", text, flags=re.IGNORECASE)
    text = re.sub(r"\bobjectt\s*s\b", "objects", text, flags=re.IGNORECASE)

    # Bracket artifact like "1.52]]\n m"
    text = re.sub(r"\]\]\s*\n\s*m\b", "] m", text)
    text = re.sub(r"\]\]\s*m\b", "] m", text)

    # Replace some TTC corruption (best-effort)
    text = text.replace("2 �~I� TTC < 5", "2 <= TTC < 5")
    text = text.replace("TTC �~I� 5", "TTC >= 5")
    text = text.replace("TTC = �~H~^", "TTC = infinity (∞)")

    # Collapse excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Strip trailing spaces
    text = "\n".join(line.rstrip() for line in text.splitlines())

    return text.strip()


def triple_quote_py(value: str) -> str:
    """
    Return a Python triple-quoted string literal content-safe.
    Escapes accidental triple quotes.
    """
    return value.replace('"""', '\\"\\"\\"')


def make_python_block(var_name: str, text: str) -> str:
    safe = triple_quote_py(text)
    return f'{var_name} = """{safe}"""\n'


def build_output_code(payload: Dict, fields: List[str], prefix: str = "") -> str:
    blocks = []
    for f in fields:
        if f not in payload:
            # If missing, still define as empty so formatting stays stable
            cleaned = ""
        else:
            v = payload[f]
            if v is None:
                cleaned = ""
            elif isinstance(v, str):
                cleaned = clean_text(v)
            else:
                # If not string, serialize to JSON (pretty) so it's still readable
                cleaned = json.dumps(v, ensure_ascii=False, indent=2)

        var = f"{prefix}{f}_clean" if prefix else f"{f}_clean"
        blocks.append(make_python_block(var, cleaned))

    # Pretty print section
    print_section = "\n".join(
        [
            "print('=== system_prompt ===')",
            "print(system_prompt_clean)",
            "print()",
            "print('=== prompt ===')",
            "print(prompt_clean)",
            "print()",
            "print('=== response ===')",
            "print(response_clean)",
        ]
    )
    return (
        "# Auto-generated by convert_prompt_fields.py\n"
        "# Extracted & cleaned fields: system_prompt, prompt, response\n\n"
        + "\n".join(blocks)
        + "\n"
        + print_section
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Extract system_prompt/prompt/response from a JSON file, clean them, and output pretty Python multiline strings."
    )
    parser.add_argument("json_path", type=str, help="Path to input .json file")
    parser.add_argument(
        "--fields",
        nargs="+",
        default=DEFAULT_FIELDS,
        help='Fields to extract (default: system_prompt prompt response)',
    )
    parser.add_argument(
        "--out",
        type=str,
        default="",
        help="Optional output path (e.g., cleaned_fields.py). If omitted, prints to stdout.",
    )
    args = parser.parse_args()

    json_file = Path(args.json_path)
    if not json_file.exists():
        raise FileNotFoundError(f"JSON file not found: {json_file}")

    with json_file.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    if not isinstance(payload, dict):
        raise TypeError("Input JSON must be an object/dict at the top level.")

    # Validate fields exist (soft: allow missing, but warn via comments)
    out_code = build_output_code(payload, fields=args.fields)

    if args.out:
        Path(args.out).write_text(out_code, encoding="utf-8")
    else:
        print(out_code)


if __name__ == "__main__":
    main()

